In [1]:
from io import StringIO
import pandas as pd

csvString = """,timeStamp,light,moisture,class
0,1646105983670,0.249023438,0.002929688,sunny
1,1646105984670,0.247070313,0.002929688,sunny
2,1646105985670,0.244140625,0.002929688,sunny
3,1646105986669,0.2421875,0.002929688,sunny
4,1646105987669,0.241210938,0.002929688,sunny
5,1646105988670,0.239257813,0.002929688,sunny
6,1646105989670,0.239257813,0.002929688,sunny
7,1646105990669,0.237304688,0.002929688,sunny
8,1646105991678,0.236328125,0.002929688,sunny
9,1646105992671,0.234375,0.002929688,sunny
10,1646105993670,0.232421875,0.002929688,sunny
11,1646105994671,0.232421875,0.002929688,sunny
12,1646105995669,0.234375,0.002929688,sunny
13,1646105996669,0.232421875,0.002929688,sunny
14,1646105997670,0.232421875,0.002929688,sunny
15,1646105998670,0.232421875,0.002929688,sunny
16,1646105999670,0.232421875,0.002929688,sunny
17,1646106000670,0.234375,0.002929688,sunny
18,1646106001670,0.236328125,0.002929688,sunny
19,1646106002672,0.239257813,0.002929688,sunny
20,1646106003671,0.243164063,0.002929688,sunny
21,1646106004670,0.247070313,0.002929688,sunny
22,1646106005670,0.250976563,0.002929688,sunny
23,1646106006670,0.254882813,0.002929688,sunny
24,1646106007670,0.255859375,0.002929688,sunny
25,1646106008672,0.262695313,0.002929688,sunny
26,1646106009670,0.265625,0.002929688,sunny
27,1646106010670,0.26953125,0.002929688,sunny
28,1646106011669,0.275390625,0.002929688,sunny
29,1646106012669,0.276367188,0.002929688,sunny
0,1646106101669,0.5234375,0.002929688,cloudy
1,1646106102670,0.52734375,0.002929688,cloudy
2,1646106103670,0.52734375,0.002929688,cloudy
3,1646106104669,0.53125,0.002929688,cloudy
4,1646106105669,0.528320313,0.002929688,cloudy
5,1646106106669,0.528320313,0.002929688,cloudy
6,1646106107669,0.529296875,0.002929688,cloudy
7,1646106108669,0.52734375,0.002929688,cloudy
8,1646106109670,0.52734375,0.002929688,cloudy
9,1646106110670,0.529296875,0.002929688,cloudy
10,1646106111671,0.53125,0.002929688,cloudy
11,1646106112669,0.530273438,0.002929688,cloudy
12,1646106113670,0.533203125,0.002929688,cloudy
13,1646106114670,0.534179688,0.00390625,cloudy
14,1646106115670,0.536132813,0.002929688,cloudy
15,1646106116670,0.537109375,0.002929688,cloudy
16,1646106117670,0.541992188,0.002929688,cloudy
17,1646106118669,0.541992188,0.002929688,cloudy
18,1646106119670,0.541992188,0.002929688,cloudy
19,1646106120670,0.544921875,0.002929688,cloudy
20,1646106121670,0.546875,0.002929688,cloudy
21,1646106122671,0.547851563,0.002929688,cloudy
22,1646106123670,0.547851563,0.002929688,cloudy
23,1646106124670,0.546875,0.002929688,cloudy
24,1646106125670,0.543945313,0.002929688,cloudy
25,1646106126670,0.541992188,0.002929688,cloudy
26,1646106127670,0.540039063,0.002929688,cloudy
27,1646106128671,0.534179688,0.002929688,cloudy
28,1646106129670,0.53125,0.002929688,cloudy
29,1646106130673,0.528320313,0.002929688,cloudy
0,1646106209670,0.372070313,0.459960938,rainy
1,1646106210669,0.370117188,0.462890625,rainy
2,1646106211671,0.369140625,0.461914063,rainy
3,1646106212669,0.370117188,0.458007813,rainy
4,1646106213671,0.30859375,0.459960938,rainy
5,1646106214670,0.309570313,0.458007813,rainy
6,1646106215669,0.438476563,0.458984375,rainy
7,1646106216669,0.159179688,0.462890625,rainy
8,1646106217670,0.15625,0.458984375,rainy
9,1646106218670,0.15625,0.45703125,rainy
10,1646106219670,0.15625,0.455078125,rainy
11,1646106220669,0.161132813,0.451171875,rainy
12,1646106221670,0.159179688,0.453125,rainy
13,1646106222670,0.158203125,0.458984375,rainy
14,1646106223670,0.155273438,0.458984375,rainy
0,1646106259669,0.522460938,0.446289063,rainy
1,1646106260670,0.5234375,0.434570313,rainy
2,1646106261669,0.52734375,0.428710938,rainy
3,1646106262670,0.529296875,0.435546875,rainy
4,1646106263670,0.530273438,0.438476563,rainy
5,1646106264670,0.53125,0.44140625,rainy
6,1646106265674,0.53125,0.446289063,rainy
7,1646106266670,0.532226563,0.447265625,rainy
8,1646106267670,0.534179688,0.4453125,rainy
9,1646106268669,0.536132813,0.448242188,rainy
10,1646106269670,0.536132813,0.43359375,rainy
11,1646106270670,0.53515625,0.438476563,rainy
12,1646106271670,0.534179688,0.44140625,rainy
13,1646106272670,0.533203125,0.448242188,rainy
14,1646106273670,0.532226563,0.448242188,rainy"""

csvStringIO = StringIO(csvString)
data = pd.read_csv(csvStringIO, sep=",").drop(["timeStamp", "Unnamed: 0"], axis=1)  # read csv file
data.head(5)

      light  moisture  class
0  0.249023   0.00293  sunny
1  0.247070   0.00293  sunny
2  0.244141   0.00293  sunny
3  0.242188   0.00293  sunny
4  0.241211   0.00293  sunny